### ISSUE TITLE
How to use from different plugins with event listeners

### ISSUE THREAD

**Issue by checkerap** [hybridgroup/cylon-audio#11]

**Comment by checkerap** [comment]
I'm new to cylon and nodejs in general. I'm using this plugin from my custom plugins like this:
this.robot.audio.play(filename);

Is this the correct way?

I also have the plugin listening on the complete event, but there's no way of differentiating between the sounds that completed playing (several plugins can request playing files at the same time). Or maybe I'm missing something.

I was thinking of making my own custom method, that could either return the filename in the event or allow for custom event names.

**Comment by deadprogram** [comment]
If you use a separate device each using the audio driver for each sound, you can listen for the events separately on each: https://github.com/hybridgroup/cylon-audio/blob/master/lib/driver.js#L97

Something like this should work:

```
  connections: {
    audio: { adaptor: "audio" }
  },

  devices: {
    sound1: { driver: "audio", file: "./audio_samples/audio-sample.mp3" },
    sound2: { driver: "audio", file: "./audio_samples/audio-sample2.mp3" }
  },

  work: function(my) {
    my.sound1.on("stop", function() {
        console.log("sound1 done");
    });
    my.sound2.on("stop", function() {
        console.log("sound2 done");
    });
    my.sound1.play();
    my.sound2.play();
  }
```

Hope that helps!

**Comment by checkerap** [comment]
ah, cool, that works :)
